<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite errors="0" failures="1" hostname="seba-ThinkPad-X1-Carbon-6th" name="pytest" skipped="0" tests="2" time="0.076" timestamp="2020-07-16T22:11:15.201080"><testcase classname="test_class.TestClass" file="test_class.py" line="2" name="test_one_LOMA0004" time="0.001"></testcase><testcase classname="test_class.TestClass" file="test_class.py" line="6" name="test_two" time="0.002"><failure message="AssertionError: assert False
 +  where False = hasattr(&apos;hello&apos;, &apos;check&apos;)">self = &lt;test_class.TestClass object at 0x7f2d1f791c50&gt;

    def test_two(self):
        x = &quot;hello&quot;
&gt;       assert hasattr(x, &quot;check&quot;)
E       AssertionError: assert False
E        +  where False = hasattr(&apos;hello&apos;, &apos;check&apos;)

test_class.py:9: AssertionError</failure></testcase></testsuite></testsuites>